# Introduction to PyTorch 🔥

Some points to note :- 
1. numpy doesn't run on gpu  
2. cpu not capable to do lot of smaller calculation as compare to gpu  
3. a cpu has 4-12 cores where as a gpu has thousands of cores  
4. So PyTorch is just like numpy on gpu with some nice helper functions  
5. A tensor is like an array..multidimensional array

In [1]:
import torch
import torchvision
print(torch.cuda.is_available())

False


## PyTorch Tensor

In [2]:
#One dimensional tensor is just a normal array or just a list
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [3]:
#2-D tensor or a matrix 
b = torch.tensor([[2,1,4], [3,5,4], [4,2,1], [3,4,7]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [4, 2, 1],
        [3, 4, 7]])


In [4]:
#The size of tensors
print(a.size())
print(a.shape)
print(b.size())
print(b.shape)

torch.Size([3])
torch.Size([3])
torch.Size([4, 3])
torch.Size([4, 3])


In [5]:
#Get the heigh or number of rows in b
print(b.shape[0])

4


In [6]:
#To define a float tensor
c = torch.FloatTensor([[2,1,4],[3,5,6], [1,2,0]])
print(c)
print(c.dtype)
#or we can define as 
#c = torch.tensor([[2,1,4], [3,5,6], [1,2,0]], dtype = torch.float)
#print(c)

tensor([[2., 1., 4.],
        [3., 5., 6.],
        [1., 2., 0.]])
torch.float32


In [7]:
d = torch.DoubleTensor([[2,1,5], [3,5,7], [4,5,7]])
print(d)
print(d.dtype)
#d = torch.tensor([[2,1,4], [3,5,6], [1,2,0]], dtype = torch.double)
#print(c)

tensor([[2., 1., 5.],
        [3., 5., 7.],
        [4., 5., 7.]], dtype=torch.float64)
torch.float64


> float64 and double are same

In [8]:
print(c.mean())

tensor(2.6667)


In [9]:
print(d.mean())

tensor(4.3333, dtype=torch.float64)


In [10]:
print(c.std())

tensor(2.)


In [11]:
print(d.std())

tensor(2.0616, dtype=torch.float64)


In [12]:
print(b)
print('---------------------------')
#Reshape b
print(b.view(-1,4))

tensor([[2, 1, 4],
        [3, 5, 4],
        [4, 2, 1],
        [3, 4, 7]])
---------------------------
tensor([[2, 1, 4, 3],
        [5, 4, 4, 2],
        [1, 3, 4, 7]])


In [13]:
#create a 3d tensor with  2 channels, 3 rows and 4 columns
three_dim = torch.randn(2,3,4)
print(three_dim)


tensor([[[-0.7074,  1.6480, -0.3119,  1.8656],
         [-1.0067, -1.0302,  0.3655,  0.9227],
         [-1.6328,  1.1835, -0.2267, -0.4882]],

        [[ 1.6090,  1.1417, -2.0049, -0.3159],
         [-2.1051, -1.1786,  1.5390, -0.0281],
         [ 0.9930,  0.2057, -1.4689,  0.6962]]])


In [14]:
#reshape to 2 rows and 12 columns
print(three_dim.view(2,12))

tensor([[-0.7074,  1.6480, -0.3119,  1.8656, -1.0067, -1.0302,  0.3655,  0.9227,
         -1.6328,  1.1835, -0.2267, -0.4882],
        [ 1.6090,  1.1417, -2.0049, -0.3159, -2.1051, -1.1786,  1.5390, -0.0281,
          0.9930,  0.2057, -1.4689,  0.6962]])


In [15]:
#alternate way
print(three_dim.view(2,-1))

tensor([[-0.7074,  1.6480, -0.3119,  1.8656, -1.0067, -1.0302,  0.3655,  0.9227,
         -1.6328,  1.1835, -0.2267, -0.4882],
        [ 1.6090,  1.1417, -2.0049, -0.3159, -2.1051, -1.1786,  1.5390, -0.0281,
          0.9930,  0.2057, -1.4689,  0.6962]])


In [16]:
#create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.1780, 0.5471, 0.1403, 0.2456],
        [0.4704, 0.5888, 0.0583, 0.1985],
        [0.2436, 0.9746, 0.8963, 0.7229],
        [0.0550, 0.0882, 0.1736, 0.9473]])


In [17]:
#create a matrix with random numbers taken from  a normal distribution with mean 0 and variance of 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-1.2757, -1.4779,  2.0025,  0.2972],
        [ 0.5521, -0.2533, -0.0532, -0.2204],
        [-0.0253,  1.6751, -1.6184,  0.3618],
        [ 1.3005, -2.0968,  0.7155, -0.2095]])
torch.float32


In [18]:
#create an array of 5 random integers from values between 6 and 9 (exclusive 10)
r3 = torch.randint(6,10, (5,))
print(r3)
print(r3.dtype)

tensor([8, 6, 9, 7, 7])
torch.int64


In [19]:
#create a 2-D array of size 3x3 filled with random integers from values 6 and 9 (exclusive of 10)
r4 = torch.randint(6,10, (3,3))
print(r4)

tensor([[8, 8, 7],
        [9, 6, 8],
        [6, 6, 6]])


In [20]:
#Get the number of elements in array
print(torch.numel(r4))
print(torch.numel(r3))

9
5


In [21]:
#create a 3x3 matrix of zeros and dtype of long 
z = torch.zeros(3,3,dtype = torch.long)
print(z)

#construct a 3x3 matrix of ones 
o = torch.ones(3,3)
print(o)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [22]:
#Convert the data type of the tensor
r2_like  = torch.randn_like(r2, dtype = torch.double)
print(r2_like)
print(r2_like.dtype)

tensor([[ 0.3031, -1.1381, -1.5346, -0.0392],
        [-1.2925,  0.3874, -0.5771,  0.7902],
        [ 0.0191, -0.1143, -0.1777, -2.0918],
        [-1.3411, -0.0622,  0.6044, -0.2578]], dtype=torch.float64)
torch.float64


In [23]:
#Add two tensors, make  sure they are the same size and same data type
add_result = torch.add(r,r2)
print(add_result)

tensor([[-1.0977, -0.9308,  2.1427,  0.5429],
        [ 1.0226,  0.3355,  0.0051, -0.0219],
        [ 0.2184,  2.6497, -0.7222,  1.0847],
        [ 1.3555, -2.0086,  0.8892,  0.7378]])


In [24]:
#In place addition (change the value of r2 and no need to assign to r2 it changes r2 directly) 
r2.add_(r) # r2 = torch.add(r,r2)
print(r2)


tensor([[-1.0977, -0.9308,  2.1427,  0.5429],
        [ 1.0226,  0.3355,  0.0051, -0.0219],
        [ 0.2184,  2.6497, -0.7222,  1.0847],
        [ 1.3555, -2.0086,  0.8892,  0.7378]])


In [25]:
#slicing 
print(r2[:, 1]) #all the rows from first columns
print(r2[:, :2]) #all the rows from column 0 to 1 
print(r2[:3,:]) #all the rows untill 2 and all the columns
single_num = r2[2,3] #to extract single number
print(single_num) # this gives a tensor
print(single_num.item()) #to extract out number out of tensor
print(r2[2, :]) #from second row all the columns

tensor([-0.9308,  0.3355,  2.6497, -2.0086])
tensor([[-1.0977, -0.9308],
        [ 1.0226,  0.3355],
        [ 0.2184,  2.6497],
        [ 1.3555, -2.0086]])
tensor([[-1.0977, -0.9308,  2.1427,  0.5429],
        [ 1.0226,  0.3355,  0.0051, -0.0219],
        [ 0.2184,  2.6497, -0.7222,  1.0847]])
tensor(1.0847)
1.0846613645553589
tensor([ 0.2184,  2.6497, -0.7222,  1.0847])


## Numpy Bridge

In [26]:
# create a numpy  array
import numpy as np
x = np.array([[1,2],[3,5]])
print(x)

[[1 2]
 [3 5]]


In [27]:
#convert the numpy array to torch
y = torch.from_numpy(x)
print(y)

tensor([[1, 2],
        [3, 5]])


In [28]:
#convert a torch tensor to numpy array
z = torch.ones(3,3, dtype = torch.double)
print(z)
a = z.numpy()
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
